### ISSUE TITLE
Error with read or write into process

### ISSUE THREAD

**Issue by Bas1COP** [ALittlePatate/TaxiDriver#2]
Whenever i am trying to use the RPM or WPM i end up with error although i was just using 
process_vm_writev and process_vm_readv before idk if this will work in same way.

**Comment by ALittlePatate** [comment]
can you give me the output of the usermode app and dmseg please ?
people reported me that they had issues opening the target process thus using an invalid PID so W/RPM was failing, maybe it's also the case here

**Comment by Bas1COP** [comment]
bool Read(long address, void* pBuff, size_t size) {
        if (size == 0)
            return false;
        void* pAddress = (void*)address;
        pid_t pid = GetPID();
        struct iovec iovLocalAddressSpace[1]{ 0 };
        struct iovec iovRemoteAddressSpace[1]{ 0 };
        iovLocalAddressSpace[0].iov_base = pBuff;     // Store data in this buffer
        iovLocalAddressSpace[0].iov_len = size;       // which has this size.
        iovRemoteAddressSpace[0].iov_base = pAddress; // The data comes from here
        iovRemoteAddressSpace[0].iov_len = size;      // and has this size.
        ssize_t sSize = process_vm_readv(
            pid,                   // Remote process id
            iovLocalAddressSpace,  // Local iovec array
            1,                     // Size of the local iovec array
            iovRemoteAddressSpace, // Remote iovec array
            1,                     // Size of the remote iovec array
            0);                    // Flags, unused
        if (sSize == (ssize_t)size)
            return true;
        else if (sSize == 0)
            return false;
        return false;
    }

    bool Write(long address, void* pBuff, size_t size) {
        if (size == 0)
            return false;
        void* pAddress = (void*)address;
        pid_t pid = GetPID();
        struct iovec iovLocalAddressSpace[1]{ 0 };
        struct iovec iovRemoteAddressSpace[1]{ 0 };
        iovLocalAddressSpace[0].iov_base = pBuff;     // Store data in this buffer
        iovLocalAddressSpace[0].iov_len = size;       // which has this size.
        iovRemoteAddressSpace[0].iov_base = pAddress; // The data will be writted here
        iovRemoteAddressSpace[0].iov_len = size;      // and has this size.
        ssize_t sSize = process_vm_writev(
            pid,                   // Remote process id
            iovLocalAddressSpace,  // Local iovec array
            1,                     // Size of the local iovec array
            iovRemoteAddressSpace, // Remote iovec array
            1,                     // Size of the remote iovec array
            0);                    // Flags, unused
        if (sSize == (ssize_t)size)
            return true;
        else if (sSize == 0)
            return false;
        return false;
    }

    template <class T>
    T Read(long address) {
        T buffer;
        bool success = Read(address, &buffer, sizeof(T));
        if (!success) {
            m_pid = 0;
            throw std::invalid_argument(
                "Failed to get " + std::to_string(sizeof(T)) + "at: " + std::to_string(address));
        }
        return buffer;
    }

    template <class T>
    void Write(long address, T value) {
        bool success = Write(address, &value, sizeof(T));
        if (!success) {
            m_pid = 0;
            throw std::invalid_argument(
                "Failed to set " + std::to_string(sizeof(T)) + " at: " + std::to_string(address));
        }
    }

    std::string ReadString(long address, int size) {
        char buffer[size] = { 0 };
        bool success = Read(address, &buffer, size);
        if (!success)
            throw std::invalid_argument("Failed to read String at address: " + address);
        return std::string(buffer);
    }
    
    
    i was using these for rpm / wpm so do i just replace all of it with RPM and WPM cause i don't think that will work, i can really use your help on these once.
    
    i did manage to use the read and write func on kernel but when i try to replace them i get errors.

**Comment by ALittlePatate** [comment]
what errors do you have ?

**Comment by Bas1COP** [comment]
> what errors do you have ?

it can't get the level name and i get errors as can't convert this to that a lot i am using a hack called grinder please help me out bro.

**Comment by ALittlePatate** [comment]
https://www.learncpp.com/
